"""Category (b): numeric snapshot, plus the collected-test-count guard.

The snapshot is generated by `tools/snapshot_weights.py`. This file only checks
that the live values still match it.

**When this fails, do not edit the JSON by hand.** Regenerate it:

    python tools/snapshot_weights.py

and read the diff as a report of what moved. A failure here is not a bug — it is
the suite telling you a number changed and asking whether you meant it.
"""

from __future__ import annotations

import ast
import json
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
SNAPSHOT = ROOT / "tests" / "weight_snapshot.json"


def test_snapshot_matches_current_values():
    """Regenerate with `python tools/snapshot_weights.py` and review the diff."""
    import sys
    sys.path.insert(0, str(ROOT))
    from tools.snapshot_weights import build

    assert SNAPSHOT.exists(), "run tools/snapshot_weights.py"
    stored = json.loads(SNAPSHOT.read_text(encoding="utf-8"))
    current = build()

    assert current["weights"] == stored["weights"], (
        "weights moved — regenerate the snapshot and review the diff")
    assert current["routes"] == stored["routes"], (
        "route costs moved — regenerate the snapshot and review the diff")


# ------------------------------------------------------------- count guard

# Bumped deliberately when tests are added. A *drop* means tests were deleted,
# which is what happened when a patch range silently swallowed three RBCD tests
# and the total went 110 -> 107 without anything failing.
EXPECTED_MINIMUM_TESTS = 111


def test_no_tests_were_silently_deleted():
    """Counts `def test_*` across the suite by AST.

    A green run with fewer tests than before is indistinguishable from a green
    run with the same tests, which is how the RBCD deletion went unnoticed until
    the total was read by eye. If this fails after a deliberate removal, lower
    the constant in the same commit that removes them, so the drop is visible in
    review.
    """
    total = 0
    for path in sorted((ROOT / "tests").glob("test_*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        total += sum(1 for n in ast.walk(tree)
                     if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))
                     and n.name.startswith("test_"))
    assert total >= EXPECTED_MINIMUM_TESTS, (
        f"{total} tests collected, expected at least {EXPECTED_MINIMUM_TESTS}. "
        f"If tests were removed on purpose, lower the constant in the same "
        f"commit so the drop is reviewable.")
