"""Category (b): numeric snapshot, plus the test-inventory guard.

The snapshot is generated by `tools/snapshot_weights.py`. This file only checks
that the live values still match it.

**When this fails, do not edit the JSON by hand.** Regenerate it:

    python tools/snapshot_weights.py

and read the diff as a report of what moved. A failure here is not a bug — it is
the suite telling you a number changed and asking whether you meant it.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SNAPSHOT = ROOT / "tests" / "weight_snapshot.json"


def test_snapshot_matches_current_values():
    """Regenerate with `python tools/snapshot_weights.py` and review the diff."""
    import sys
    sys.path.insert(0, str(ROOT))
    from tools.snapshot_weights import build

    assert SNAPSHOT.exists(), "run tools/snapshot_weights.py"
    stored = json.loads(SNAPSHOT.read_text(encoding="utf-8"))
    current = build()

    assert current["weights"] == stored["weights"], (
        "weights moved — regenerate the snapshot and review the diff")
    assert current["routes"] == stored["routes"], (
        "route costs moved — regenerate the snapshot and review the diff")


INVENTORY = ROOT / "tests" / "test_inventory.json"


def test_no_tests_were_silently_deleted():
    """Compares the suite's test names against `tests/test_inventory.json`.

    This used to floor the *total* at a constant, which only catches net
    deletion: remove three tests and add two, and the count holds while three
    are gone. The RBCD incident was caught by a count only because nothing was
    added in the same patch — luck, not the guard working.

    Comparing name sets removes that dependence on luck. Regenerate with
    `python tools/snapshot_tests.py` in the same commit that adds or removes
    tests, so the diff carries the change into review.
    """
    import sys
    sys.path.insert(0, str(ROOT))
    from tools.snapshot_tests import collect

    assert INVENTORY.exists(), "run tools/snapshot_tests.py"
    stored = json.loads(INVENTORY.read_text(encoding="utf-8"))["tests"]
    current = collect()

    was = {(f, n) for f, names in stored.items() for n in names}
    now = {(f, n) for f, names in current.items() for n in names}

    removed = sorted(was - now)
    added = sorted(now - was)

    # Removals first and phrased as a question, because a removal that nobody
    # intended is the failure this guard exists for. An addition is routine and
    # only needs the file regenerated.
    assert not removed, (
        f"{len(removed)} test(s) in the inventory are gone from the suite: "
        f"{', '.join(f'{f}::{n}' for f, n in removed)}. If that was deliberate, "
        f"regenerate with `python tools/snapshot_tests.py` in the same commit so "
        f"the removal is visible in review. If not, they were swallowed.")
    assert not added, (
        f"{len(added)} new test(s) are not in the inventory: "
        f"{', '.join(f'{f}::{n}' for f, n in added)}. Regenerate with "
        f"`python tools/snapshot_tests.py` — until then they are unprotected, "
        f"because a later deletion would have no record to contradict.")
