"""Regenerate the test-name inventory. Category (b): facts, not claims.

    python tools/snapshot_tests.py

Writes `tests/test_inventory.json` — every `test_*` function in the suite, keyed
by file.

**Never hand-edit it, and never edit it to make a test pass.** When it changes,
read the diff as a report of which tests appeared and which disappeared, and
decide whether you meant both. Same convention as `snapshot_weights.py`.

Why a name set and not a count. The guard this replaces floored the *total* at a
constant, which catches net deletion and nothing else: remove three tests, add
two, and the total holds while three are silently gone. That is close to the
failure it was built for — a patch range once swallowed three RBCD tests and the
count went 110 -> 107 — except the count moved that time, which is the only
reason anyone noticed. A set difference does not depend on that luck.
"""

from __future__ import annotations

import ast
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INVENTORY = ROOT / "tests" / "test_inventory.json"


def collect() -> dict[str, list[str]]:
    """Every `test_*` function in the suite, keyed by file, sorted for diffing.

    `ast.walk` rather than a top-level scan so tests nested in classes are
    counted the same way the old count guard counted them.
    """
    found: dict[str, list[str]] = {}
    for path in sorted((ROOT / "tests").glob("test_*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        names = sorted(
            n.name for n in ast.walk(tree)
            if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))
            and n.name.startswith("test_")
        )
        found[path.relative_to(ROOT).as_posix()] = names
    return found


def build() -> dict:
    tests = collect()
    return {
        "_comment": "GENERATED by tools/snapshot_tests.py - do not hand-edit. "
                    "A diff here is a report of which tests came and went. "
                    "`total` is the AST count of test FUNCTIONS and is not "
                    "the `pytest -q` collected count, which expands "
                    "parametrize and is larger; the two are unrelated "
                    "numbers that have collided at 194 before.",
        "total": sum(len(v) for v in tests.values()),
        "tests": tests,
    }


if __name__ == "__main__":
    INVENTORY.write_text(json.dumps(build(), indent=2) + "\n",
                         encoding="utf-8", newline="\n")
    print(f"wrote {INVENTORY.relative_to(ROOT)}")
