"""Regenerate the numeric snapshot. Category (b): values, not claims.

    python tools/snapshot_weights.py

Writes `tests/weight_snapshot.json` — current weights, conditionals, and the
route costs for the three documented entry points on the frozen graph.

**Never hand-edit the snapshot, and never edit it to make a test pass.** When it
changes, read the diff as a report of what moved and decide whether the move was
intended. That is the whole point of separating it from
`tests/test_weight_invariants.py`, which holds claims that must break loudly.

The distinction came out of a real failure: ordering assertions were rewritten
twice in one session to agree with weights that were themselves wrong, so the
suite endorsed the error while it was live.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from stealthpath.ad_schema import DEFAULT_TRAVERSAL_SET, GPO_EXPANSION_EDGES
from stealthpath.graph import AttackGraph
from stealthpath.planners.shortest_path import dijkstra
from stealthpath.planners.weighted_astar import astar
from stealthpath.risk import PROVISIONAL_WEIGHTS, static_cost_fn, weight_of

ENTRIES = ["SAMWELL.TARLY@NORTH", "SQL_SVC@NORTH", "TYWIN.LANNISTER@SEVENKINGDOMS"]
SNAPSHOT = ROOT / "tests" / "weight_snapshot.json"
GRAPH = ROOT / "data" / "goad_graph.json"


def build() -> dict:
    weights = {
        rel: {
            "weight": w.weight,
            "sourced": w.sourced,
            "channels": list(w.channels),
            "conditional": w.conditional or {},
        }
        for rel, w in sorted(PROVISIONAL_WEIGHTS.items())
    }

    routes: dict[str, dict] = {}
    if GRAPH.exists():
        g = AttackGraph.load(GRAPH)
        view = g.with_gpo_expansion()
        allowed = DEFAULT_TRAVERSAL_SET | GPO_EXPANSION_EDGES
        targets = view.tier0_targets()
        cost = static_cost_fn()
        for entry in ENTRIES:
            src = view.find(name=entry)
            plain = dijkstra(view, src, targets, allowed_rel_types=allowed)
            weighted = astar(view, src, targets, cost, allowed_rel_types=allowed)
            routes[entry] = {
                "plain": {
                    "hops": plain.length,
                    "risk": round(sum(weight_of(r) for r in plain.rel_types(view)), 2),
                    "route": plain.rel_types(view),
                },
                "weighted": {
                    "hops": weighted.length,
                    "risk": round(weighted.cost, 2),
                    "route": weighted.rel_types(view),
                },
                "planners_differ": plain.rel_types(view) != weighted.rel_types(view),
            }

    return {
        "_comment": "GENERATED by tools/snapshot_weights.py - do not hand-edit. "
                    "A diff here is a report of what moved, not a test to fix.",
        "graph": "data/goad_graph.json",
        "sourced_count": sum(1 for w in PROVISIONAL_WEIGHTS.values() if w.sourced),
        "total_count": len(PROVISIONAL_WEIGHTS),
        "weights": weights,
        "routes": routes,
    }


if __name__ == "__main__":
    SNAPSHOT.write_text(json.dumps(build(), indent=2) + "\n",
                        encoding="utf-8", newline="\n")
    print(f"wrote {SNAPSHOT.relative_to(ROOT)}")
